import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const navigation = {
  docsSidebar: [{ type: "autogenerated", dirName: "." }],
} satisfies SidebarsConfig;

export default navigation;
