name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: ["*"]

jobs:
  all:
    name: all
    runs-on: ubuntu-latest

    permissions:
      contents: read
      deployments: write

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn

      - run: corepack enable && yarn install --immutable

      - run: yarn run build

      - name: Deploy
        uses: cloudflare/pages-action@v1
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          gitHubToken: ${{ github.token }}
          branch: ${{ github.head_ref || github.ref_name }}
          projectName: foxglove-docs
          directory: build
